version: '3.4'

networks:
  dev:
    driver: bridge

services:
  basebackend:
    image: bksbackend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5041:80
      - 7196:443 
    depends_on:
      - "basedb"
    networks:
      - dev

  basedb:
    image: postgres:latest
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data/
    container_name: basedb
    environment:
      - POSTGRES_USER=baseuser
      - POSTGRES_PASSWORD=baseuser123
      - POSTGRES_DB=basedb
    ports:
      - 5433:5432
    networks:
      - dev

volumes:
  db_volume: